2024-10-22 19:00:14 - ERROR - Unable to find dataframe
Traceback (most recent call last):
  File "C:\personal\programming\config_Project\main.py", line 161, in main
    filledTemplate = fill_rung_template(root, rungNum, rung)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\programming\config_Project\main.py", line 44, in fill_rung_template
    oldRung = RLLContent.xpath(f"//Rung[containes(@Number, {rungNum})]")
              ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'xpath'
2024-10-28 09:38:22 - CRITICAL - No Excel File
2024-10-28 09:38:22 - CRITICAL - No L5X File
2024-10-28 09:38:22 - ERROR - General Error creating dataframe
Traceback (most recent call last):
  File "C:\personal\programming\config_Project\utilities\excel_utils.py", line 32, in open_excel_as_pd
    sheet = pd.read_excel(excelPath, sheet_name=sheetName)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\programming\config_Project\configenv\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "C:\personal\programming\config_Project\configenv\Lib\site-packages\pandas\io\excel\_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\programming\config_Project\configenv\Lib\site-packages\pandas\io\excel\_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "C:\personal\programming\config_Project\configenv\Lib\site-packages\pandas\io\common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\personal\programming\config_Project\configenv\Lib\site-packages\pandas\io\common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
2024-10-28 09:38:22 - ERROR - Unable to find dataframe
Traceback (most recent call last):
  File "C:\personal\programming\config_Project\main.py", line 150, in main
    for fileName, rungs in dataframe.items():
                           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
